spring.config.import=optional:file:.env
spring.application.name=scm2.0

server.port=9192
spring.thymeleaf.cache=false


#mysql database configurations
#datasource url
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#jpa configurations
#to show the jpa properties on console.
spring.jpa.show-sql=true
#for creating the schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#to determine the database it also automatically get added using mysql jar files.
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

#security configurations

#spring.security.user.name=saumya
#spring.security.user.password=saumya123

# oauth2 configurations
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

#github configure
spring.security.oauth2.client.registration.github.client-name=GitHub
spring.security.oauth2.client.registration.github.client-id=${GIT_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GIT_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email



#cloudinary configurations
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


# allow up to 10MB per file
spring.servlet.multipart.max-file-size=10MB

# allow up to 10MB per request (all files combined)
spring.servlet.multipart.max-request-size=10MB


spring.profiles.active=dev

# razorpay id and secret
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}


#Emailjs configurations
emailjs.public-key=${EMAILJS_PUBLIC_KEY}
emailjs.service-id=${EMAILJS_SERVICE_ID}
emailjs.template-id=${EMAILJS_TEMPLATE_ID}