package com.scm.repositories;

import org.springframework.stereotype.Repository;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import com.scm.entities.User;

@Repository
// this repo has all that methods which help to interact with databases
public interface UserRepo extends JpaRepository<User, String> {
  // extra methods db relatedoperations
  // custom query methods
  // custom finder methods

  Optional<User> findByEmail(String email); // find user by email with optional and we dont have to write the queries it
  // automatically generated by jparepository.

  Optional<User> findByEmailAndPassword(String email, String password); // find user by email and password with optional
  // and we dont have to write the queries it automatically generated by
  // jparepository.Iski implementation spring jpa automatically krta we dont have
  // to mention anything manually.

  Optional<User> findByName(String name); // find user by username with optional and we dont have to write the
  // queries it automatically generated by jparepository.

  User getUserByEmail(String email); // get user by email

}
